name: CI/CD Pipeline

on:
    push:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build Backend
        run: |
          cd backend
          mvn clean package -DskipTests
          docker build -t backend .

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          docker build -t frontend .

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment/k8s/
